channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.2
- pip:
  - mlflow==3.5.0
  - cloudpickle==3.0.0
  - lz4==4.3.2
  - numpy==2.2.6
  - pandas==2.3.2
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
